### ISSUE TITLE
scanDevicesForSinglePort ping iOS not working

### ISSUE THREAD

**Issue by rainbowMehBerdaya** [osociety/network_tools#107]
HostScanner.scanDevicesForSinglePort for iOS not working

From dependency documentation
I think this should add this package `dart_ping_ios`

as said in `dart_ping` docs

> To use dart_ping on iOS, add the [dart_ping_ios](https://pub.dev/packages/dart_ping_ios) package as a dependency and register the iOS plugin before initializing Ping. For more detailed docs, see the [dart_ping_ios](https://pub.dev/packages/dart_ping_ios) package. Note that the iOS plugin requires the flutter sdk. (this is why it is not integrated into dart_ping directly)

Thank you for the package!

**Comment by git-elliot** [comment]
I guess its the time we work on network_tools_flutter package @guyluz11 . Since we cannot add dart_ping_ios in network_tools as a dependency

**Comment by guyluz11** [comment]
Cool, maybe there are some flutter-only packages that we can use to add new functionality to more stuff

**Comment by rainbowMehBerdaya** [comment]
Why can't you guys add `dart_ping_ios` to the `network_tools` package? 
I tried running it with this code, and it worked, but I'm not sure if it's the most practical solution.

```dart
static Stream<ActiveHost> scanDevicesForSinglePort(
    String subnet,
    int port, {
    int firstHostId = defaultFirstHostId,
    int lastHostId = defaultLastHostId,
    Duration timeout = const Duration(milliseconds: 2000),
    ProgressCallback? progressCallback,
    bool resultsInAddressAscendingOrder = true,
  }) async* {
    if (Platform.isIOS) {
      DartPingIOS.register();
    }

    final int lastValidSubnet =
        _validateAndGetLastValidSubnet(subnet, firstHostId, lastHostId);
    final List<Future<ActiveHost?>> activeHostOpenPortList = [];
    final StreamController<ActiveHost> activeHostsController =
        StreamController<ActiveHost>();

    for (int i = firstHostId; i <= lastValidSubnet; i++) {
      final host = '$subnet.$i';
      activeHostOpenPortList.add(
        PortScanner.connectToPort(
          address: host,
          port: port,
          timeout: timeout,
          activeHostsController: activeHostsController,
        ),
      );
    }

    if (!resultsInAddressAscendingOrder) {
      yield* activeHostsController.stream;
    }

    int counter = firstHostId;
    for (final Future<ActiveHost?> openPortActiveHostFuture
        in activeHostOpenPortList) {
      final ActiveHost? activeHost = await openPortActiveHostFuture;
      if (activeHost != null) {
        yield activeHost;
      }
      progressCallback?.call(
        (counter - firstHostId) * 100 / (lastValidSubnet - firstHostId),
      );
      counter++;
    }
  }
```

**Comment by git-elliot** [comment]
@rainbowMehBerdaya you add below code in your main class, it will work. don't forget to add dart_ping_ios as dependency in your project until network_tools_flutter is published. 
  if (Platform.isIOS) {
      DartPingIOS.register();
  }

**Comment by rainbowMehBerdaya** [comment]
Yes, I have already tried that and it's running well
I have shared the code in my previous comment.
Thank you.

**Comment by git-elliot** [comment]
We will keep this open to remind us in finishing network_tools_flutter package

**Comment by git-elliot** [comment]
@rainbowMehBerdaya network_tools_flutter package is now available for testing purpose - https://github.com/osociety/network_tools_flutter. Please try and give feedback by reopening this issue.
