### ISSUE TITLE
More points in pub dev

### ISSUE THREAD

**Issue by guyluz11** [osociety/network_tools#108]
I looks like pub dev is reducing points for us for documentation of deprecated values 

![image](https://user-images.githubusercontent.com/9304740/227516239-68c505c8-dba1-4794-8fbe-8da0bde44665.png)

**Comment by git-elliot** [comment]
but what about anaylsis_options? I added a rule for this. 
https://github.com/osociety/network_tools/blob/4f996755b82fb507d7b725efcb99715f56e818b3/network_tools/analysis_options.yaml#L15

**Comment by guyluz11** [comment]
I think that analysis options do not affect pub.dev

If it could affect positive people would have added ignore all would get the maximum points.

**Comment by git-elliot** [comment]
we will close this when we have full points in pub.dev

**Comment by git-elliot** [comment]
Point latest problems for degraded score - https://pub.dev/packages/network_tools/score
