### ISSUE TITLE
Using 3.2.7 causes crash when try to ping local network

### ISSUE THREAD

**Issue by kostadin24** [osociety/network_tools#148]
Hello, I have Flutter project supporting Android, iOS, MacOS, Linux and Windows.
Ping work nice on mobiles, but when upgraded network_tools from 3.2.2 to 3.2.7 I saw exception calling HostScanner.getAllPingableDevices:

"SqfliteFfiException(error, Invalid argument(s): Failed to load dynamic library '/data/data/com.myapp/lib/libsqlite3.so': dlopen failed: library "/data/data/com.myapp/lib/libsqlite3.so" not found}) DatabaseException(Invalid argument(s): Failed to load dynamic library '/data/data/com.myapp/lib/libsqlite3.so': dlopen failed: library "/data/data/com.myapp/lib/libsqlite3.so" not found)"

Stack trace says it is in ArpTable function. Can reproduce it again next days to send you have whole stacktrace.

Using 3.2.2 there were no issue. Switched to 3.2.7 yesterday and noticed this error.
My project crashes on Android. Didn't test other platforms.
Flutter is 3.13.4

**Comment by alaindeseine** [comment]
Hi, 
Got same problem with mdns scan

**Comment by git-elliot** [comment]
Thank you for letting me know. I'm working on this.

**Comment by git-elliot** [comment]
@kostadin24 @alaindeseine I've published the fixes try version v4.0.1 and do not forget to configure the package - https://github.com/osociety/network_tools?tab=readme-ov-file#configure-network-tools-in-main-function

**Comment by kostadin24** [comment]
It works now.
