### ISSUE TITLE
Port scan example not working

### ISSUE THREAD

**Issue by guyluz11** [osociety/network_tools#158]
An example of `port_scan` does not seem to find my local server.
Version 4.0.1

I tested also in network_tools_flutter and it didn't work.

I tested on an old version  `2ec84c604c10d2b5f6640d1e97d80628ab0ed402`  and it worked, so it regression.

**Comment by git-elliot** [comment]
Logs are not printed by default, debugging is off. Please configure debugging yourself

**Comment by guyluz11** [comment]
Ho ok
Thanks
