### ISSUE TITLE
Function to get router IP and this device IP

### ISSUE THREAD

**Issue by guyluz11** [osociety/network_tools#16]
Can we add a function to get the router/default gateway
IP and this device IP?.

**Comment by git-elliot** [comment]
`network_info_plus` package is not compatible with dart native but our package is. Apart from that is there any way we can retrieve this information?

**Comment by guyluz11** [comment]
I know in Linux how to get IP but we need to support android and ios as well.

So let's keep this up in case anybody wants to take it.

**Comment by git-elliot** [comment]
This can also be achieved by adding `network_info_plus` wherever needed

**Comment by guyluz11** [comment]
I think we should strive to have support for Android and iOS as well even if under the hood is used other packages.
This way users can call one function for platforms.

I would expect from Network tools package to have this functionality included

**Comment by git-elliot** [comment]
then it will become our responsibility to change method signature or api signature whenever these packages gets updated and also updating dependencies as those packages updates will make our job tough
