### ISSUE TITLE
Vendor table key must be upper-case

### ISSUE THREAD

**Issue by kengu** [osociety/network_tools#178]
**Problem**
Vendor information is always null, even for known mac-address ranges.

**Analysis** 
Keys in [mac-vendors-export.csv](https://raw.githubusercontent.com/osociety/network_tools/main/lib/assets/mac-vendors-export.csv) are semicolon-separated in upper case.  

On [line 20 in VendorTable](https://github.com/osociety/network_tools/blob/dev/lib/src/device_info/vendor_table.dart#L20) the first three mac address parts is joined without upper case.

**Resolution**
Add `.toUpperCase()`to `arpData.macAddress.split(pattern).sublist(0, 3).join()`on line 20

**Comment by guyluz11** [comment]
Nice catch

**Comment by guyluz11** [comment]
Closing, will be merged in the new version.

Thanks
