### ISSUE TITLE
 The argument type 'InternetAddress/*1*/' can't be assigned to the parameter type 'InternetAddress/*2*/

### ISSUE THREAD

**Issue by emme1009** [osociety/network_tools#185]
Since upgrading to flutter 3.19.1 I´m no longer able to build my app for web. The code is not used in web and was working fine before. 

Any suggestion would help.

I looked through your code and my own code. I found no import of dart.io anywhere. So I don´t know what to do next. 

```
AppData/Local/Pub/Cache/hosted/pub.dev/network_tools-4.0.4/lib/src/mdns_scanner/mdns_scanner.dart:125:31:
Error: The argument type 'InternetAddress/*1*/' can't be assigned to the parameter type 'InternetAddress/*2*/'.
 - 'InternetAddress/*1*/' is from 'dart:io'.
 - 'InternetAddress/*2*/' is from 'package:universal_io/src/internet_address.dart' ('/AppData/Local/Pub/Cache/hosted/pub.dev/universal_io-2.2.2/lib/src/internet_address.dart').
          internetAddress: ip.address,
```

**Comment by git-elliot** [comment]
Hi @emme1009 please refer to similar thread https://github.com/osociety/network_tools/issues/83 and see if anything helps.
