### ISSUE TITLE
Change name to more relevant or correct form for firstsubnet and lastsubnet.

### ISSUE THREAD

**Issue by git-elliot** [osociety/network_tools#28]
https://github.com/git-elliot/network_tools/blob/4af37d3f7be27631f3811685f2475279b3bcd4e0/lib/src/host_scanner.dart#L20-L21

What I feel now is this should be firstHostId and lastHostId.

**Comment by AviAvinav** [comment]
Just making sure, we have to change the name of `firstSubnet` & `lastSubnet`, right?

**Comment by AviAvinav** [comment]
Can you please assign this issue to me

**Comment by git-elliot** [comment]
> Just making sure, we have to change the name of `firstSubnet` & `lastSubnet`, right?

You have to change it everywhere in the code, what you can do is use "Find and Replace" so that no mistake is there.
