### ISSUE TITLE
Add support for Wake on LAN

### ISSUE THREAD

**Issue by guyluz11** [osociety/network_tools#31]
It seems that this option is popular in other network tools and maybe not so hard to implement.

**Comment by guyluz11** [comment]
Found a package for that, it also supports dart so we can just use it.

https://pub.dev/packages/wake_on_lan

**Comment by git-elliot** [comment]
@guyluz11 how you want to use this package? can you list down an example? If no use case then people can add this package directly in their project.

**Comment by guyluz11** [comment]
Ok so if this feature will be requested again we will reopen this issue
