### ISSUE TITLE
`HostScanner.discover` should run inside an isolate by default

### ISSUE THREAD

**Issue by ivirtex** [osociety/network_tools#42]
Since `HostScanner.discover` runs on the main thread, the whole UI freezes until host discovery finishes. This means more work for the developers und unnecessary confusion.
Putting the whole process inside an isolate would unblock app interaction.

**Comment by git-elliot** [comment]
Isn't it possible to run the required methods inside `[compute()](https://docs-flutter-io.firebaseapp.com/flutter/foundation/compute.html)` from flutter's foundation library.

**Comment by ivirtex** [comment]
I don't think so, it is possible when working with futures, but not streams.

**Comment by guyluz11** [comment]
Maybe we can close the issue now, @ivirtex can you test it ?

![image](https://user-images.githubusercontent.com/9304740/226112856-518a38d5-ab5c-4032-8516-07649f0d63fb.png)

**Comment by ivirtex** [comment]
Yeah, great job!
