### ISSUE TITLE
mdns_scanner crash if started without any network

### ISSUE THREAD

**Issue by guyluz11** [osociety/network_tools#60]
When I am starting mDNS search without any connected network I am expecting it to return an empty result.
But I am getting crash that is not being handled.

Log from my program (running on dart native):

```dart
Unhandled exception:
SocketException: Send failed (OS Error: Network is unreachable, errno = 101), address = 0.0.0.0, port = 5353
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1213:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2450:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:225:14)
#3      MdnsScanner._findingMdnsWithAddress (package:network_tools/src/mdns_scanner/mdns_scanner.dart:71:54)
<asynchronous suspension>
#4      MdnsScanner.searchMdnsDevices (package:network_tools/src/mdns_scanner/mdns_scanner.dart:41:29)
<asynchronous suspension>
#5      CompaniesConnectorConjector.searchAllMdnsDevicesAndSetThemUp (package:cbj_hub/infrastructure/devices/companies_connector_conjector.dart:144:43)
<asynchronous suspension>
```

**Comment by git-elliot** [comment]
Handling this error inside package can hide the fact that app is not connected to network. Empty Result can also mean that there is no device and you are connected to network. Empty result can be ambiguous in internet issue case.

**Comment by git-elliot** [comment]
Yeah just rethrow it. Developers will handle it.

**Comment by git-elliot** [comment]
I think no need to catch and rethrow if we are not doing anything extra in handling of exception. Users can themselves catch it.
