### ISSUE TITLE
Error when adding package to project. - Error: The argument type 'InternetAddress/*1*/' can't be assigned to the parameter type 'InternetAddress/*2*/'

### ISSUE THREAD

**Issue by Tmarks2a** [osociety/network_tools#83]
{user}/AppData/Local/Pub/Cache/hosted/pub.dev/network_tools-3.0.0+3/lib/src/mdns_scanner/mdns_scanner.dart:102:28: Error: The argument type 'InternetAddress/*1*/' can't be assigned to the parameter type 'InternetAddress/*2*/'.
 - 'InternetAddress/*1*/' is from 'dart:io'.
- 'InternetAddress/*2*/' is from 'package:universal_io/src/internet_address.dart' ('/{user}/AppData/Local/Pub/Cache/hosted/pub.dev/universal_io-2.2.0/lib/src/internet_address.dart').
internet_address.dart:1
          internetAddress: internetAddress,

**Comment by guyluz11** [comment]
Hi @Tmarks2a 
Can you please add more info about the crash?
What os and version did you run it on
Did it run on dart native or flutter 
Does it work on the previous version before we added `universal_io`

**Comment by git-elliot** [comment]
Similar to this is https://github.com/dint-dev/universal_io/issues/19

**Comment by guyluz11** [comment]
> Similar to this is [dint-dev/universal_io#19](https://github.com/dint-dev/universal_io/issues/19)

Nice catch @git-elliot 

Someone suggested there some work around, so if we can reproduce it it is another fix that we can take

**Comment by git-elliot** [comment]
@Tmarks2a  I'm not able to reproduce this on latest version of network_tools and flutter. Snippet I tried running 
```dart
  MdnsScanner.findingMdnsWithAddress("_airplay").then((value) {
      for (ActiveHost activeHost in value) {
        InternetAddress address = activeHost.internetAddress;
        print(address);
      }
    });
```
Not to forget InternetAddress can either be imported from universal_io/io.dart or dart:io. Code works for both imports.
[main.dart.txt](https://github.com/osociety/network_tools/files/10874092/main.dart.txt)

**Comment by git-elliot** [comment]
Please reopen if still facing the issue.
